# Black - Code formatter
[tool.black]
line-length = 100
target-version = ['py311']

# isort - Import sorting 
[tool.isort]
profile = "black"
line_length = 100

# flake8 - Linting
[tool.flake8]
max-line-length = 100
ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", ".venv", "venv"]
